/**
 * Beige first-time setup.
 *
 * Copies bundled tool packages into ~/.beige/tools/ and writes a default
 * config.json5 when none exists.  All operations are safe to re-run: existing
 * files/directories are never overwritten.
 *
 * Source-install detection
 * ────────────────────────
 * When beige is run from a git clone (i.e. the developer installed deps with
 * `npm install` / `pnpm install` but did not publish to npm) there is a `.git`
 * directory sitting next to `package.json`.  In that case we skip automatic
 * first-run setup entirely — the developer works directly from the repo.
 *
 * npm-global-install detection
 * ────────────────────────────
 * When installed via `npm install -g beige` there is no `.git` directory in the
 * package root, so `isSourceInstall()` returns false and setup can proceed.
 */

import {
  existsSync,
  mkdirSync,
  writeFileSync,
  readdirSync,
  cpSync,
  statSync,
} from "fs";
import { resolve, join } from "path";
import { homedir } from "os";
import { fileURLToPath } from "url";

// ── Resolve package root ─────────────────────────────────────────────────────

/** Absolute path to the beige package root (where package.json lives). */
function packageRoot(): string {
  // In compiled output this file is at <root>/dist/install.js
  const distDir = fileURLToPath(new URL(".", import.meta.url));
  return resolve(distDir, "..");
}

// ── Source-install guard ─────────────────────────────────────────────────────

/**
 * Returns true when beige is being run directly from a git checkout.
 * A `.git` entry at the package root is the canonical signal.
 */
export function isSourceInstall(): boolean {
  return existsSync(resolve(packageRoot(), ".git"));
}

// ── Default config template ──────────────────────────────────────────────────

function defaultConfig(kvToolPath: string): string {
  return `{
  // Beige default configuration — generated by 'beige setup'.
  // Edit freely. This file will never be overwritten by beige.

  llm: {
    providers: {
      anthropic: {
        // Set your API key here or via the ANTHROPIC_API_KEY environment variable.
        apiKey: "\${ANTHROPIC_API_KEY}",
      },
    },
  },

  tools: {
    kv: {
      // Persists key-value data across sessions on the gateway host.
      path: "${kvToolPath}",
      target: "gateway",
    },
  },

  agents: {
    beige: {
      model: {
        provider: "anthropic",
        model: "claude-sonnet-4-20250514",
        thinkingLevel: "off",
      },
      tools: ["kv"],
      sandbox: {
        image: "beige-sandbox:latest",
      },
    },
  },
}
`;
}

// ── Helpers ──────────────────────────────────────────────────────────────────

function ensureDir(p: string): void {
  mkdirSync(p, { recursive: true });
}

/**
 * Copy src → dst only if dst does not already exist.
 * Works for both files and directories (recursive).
 * Returns true when the copy was performed.
 */
function safeCopy(src: string, dst: string): boolean {
  if (existsSync(dst)) return false;

  const stat = statSync(src);
  if (stat.isDirectory()) {
    cpSync(src, dst, { recursive: true });
  } else {
    writeFileSync(dst, ""); // create placeholder so cpSync isn't needed for files
    cpSync(src, dst);
  }
  return true;
}

// ── Public API ───────────────────────────────────────────────────────────────

export interface SetupResult {
  /** Paths that were newly created. */
  created: string[];
  /** Paths that already existed and were skipped. */
  skipped: string[];
}

/**
 * Run beige first-time setup.
 *
 * @param force  When true, run even on a source install (used by `beige setup`).
 */
export async function runSetup(options: { force?: boolean } = {}): Promise<SetupResult> {
  const created: string[] = [];
  const skipped: string[] = [];

  if (!options.force && isSourceInstall()) {
    // Never auto-setup when running from source.
    return { created, skipped };
  }

  const beigeDir = resolve(homedir(), ".beige");
  const toolsDst = resolve(beigeDir, "tools");
  const configDst = resolve(beigeDir, "config.json5");

  ensureDir(beigeDir);

  // ── Copy bundled tools ─────────────────────────────────────────────────────

  const toolsSrc = resolve(packageRoot(), "tools");

  if (existsSync(toolsSrc)) {
    ensureDir(toolsDst);

    const toolEntries = readdirSync(toolsSrc);
    for (const entry of toolEntries) {
      const src = join(toolsSrc, entry);
      const dst = join(toolsDst, entry);
      const copied = safeCopy(src, dst);
      if (copied) {
        created.push(dst);
      } else {
        skipped.push(dst);
      }
    }
  }

  // ── Write default config ───────────────────────────────────────────────────

  if (existsSync(configDst)) {
    skipped.push(configDst);
  } else {
    const kvToolPath = resolve(toolsDst, "kv");
    writeFileSync(configDst, defaultConfig(kvToolPath), "utf-8");
    created.push(configDst);
  }

  return { created, skipped };
}
