/**
 * Beige first-time setup.
 *
 * Writes a default config.json5 when none exists. All operations are safe
 * to re-run: existing files are never overwritten.
 *
 * The target directory is controlled by the BEIGE_HOME environment variable
 * (see src/paths.ts).  `pnpm run beige` sets BEIGE_HOME=./.beige so that
 * source-checkout runs are self-contained inside the repo and never touch the
 * global ~/.beige used by the npm-global install.
 */

import { existsSync, mkdirSync, writeFileSync } from "fs";
import { resolve } from "path";
import { beigeDir } from "./paths.js";

// ── Default config template ──────────────────────────────────────────────────

function defaultConfig(): string {
  return `{
  // Beige default configuration — generated by 'beige setup'.
  // Edit freely. This file will never be overwritten by beige.

  // Enables editor autocomplete and validation (VS Code, JetBrains, etc.)
  $schema: "https://raw.githubusercontent.com/matthias-hausberger/beige/main/config.schema.json",

  llm: {
    providers: {
      anthropic: {
        // Set your API key here or via the ANTHROPIC_API_KEY environment variable.
        apiKey: "\${ANTHROPIC_API_KEY}",
      },
    },
  },

  // Install plugins to add tools, channels, and more:
  //   beige plugins install npm:@matthias-hausberger/beige-toolkit
  //
  // plugins: {
  //   git: { /* auto-discovered from installed plugins */ },
  // },

  agents: {
    beige: {
      model: {
        provider: "anthropic",
        model: "claude-sonnet-4-6",
        thinkingLevel: "off",
      },
      tools: [],
      sandbox: {
        image: "beige-sandbox:latest",
      },
    },
  },
}
`;
}

// ── Public API ───────────────────────────────────────────────────────────────

export interface SetupResult {
  /** Paths that were newly created. */
  created: string[];
  /** Paths that already existed and were skipped. */
  skipped: string[];
}

/**
 * Run beige first-time setup.
 */
export async function runSetup(_options: { force?: boolean } = {}): Promise<SetupResult> {
  const created: string[] = [];
  const skipped: string[] = [];

  const dir = beigeDir();
  const configDst = resolve(dir, "config.json5");

  mkdirSync(dir, { recursive: true });

  // ── Write default config ───────────────────────────────────────────────────

  if (existsSync(configDst)) {
    skipped.push(configDst);
  } else {
    writeFileSync(configDst, defaultConfig(), "utf-8");
    created.push(configDst);
  }

  return { created, skipped };
}
