/**
 * Beige first-time setup.
 *
 * Copies bundled tool packages into <beigeDir>/tools/ and writes a default
 * config.json5 when none exists.  All operations are safe to re-run: existing
 * files/directories are never overwritten.
 *
 * The target directory is controlled by the BEIGE_HOME environment variable
 * (see src/paths.ts).  `pnpm run beige` sets BEIGE_HOME=./.beige so that
 * source-checkout runs are self-contained inside the repo and never touch the
 * global ~/.beige used by the npm-global install.
 */

import {
  existsSync,
  mkdirSync,
  writeFileSync,
  readdirSync,
  cpSync,
  statSync,
} from "fs";
import { resolve, join } from "path";
import { fileURLToPath } from "url";
import { beigeDir } from "./paths.js";

// ── Resolve package root ─────────────────────────────────────────────────────

/** Absolute path to the beige package root (where package.json lives). */
function packageRoot(): string {
  // In compiled output this file is at <root>/dist/install.js
  const distDir = fileURLToPath(new URL(".", import.meta.url));
  return resolve(distDir, "..");
}

// ── Default config template ──────────────────────────────────────────────────

function defaultConfig(kvToolPath: string): string {
  return `{
  // Beige default configuration — generated by 'beige setup'.
  // Edit freely. This file will never be overwritten by beige.

  // Enables editor autocomplete and validation (VS Code, JetBrains, etc.)
  $schema: "https://raw.githubusercontent.com/matthias-hausberger/beige/main/config.schema.json",

  llm: {
    providers: {
      anthropic: {
        // Set your API key here or via the ANTHROPIC_API_KEY environment variable.
        apiKey: "\${ANTHROPIC_API_KEY}",
      },
    },
  },

  tools: {
    kv: {
      // Persists key-value data across sessions on the gateway host.
      path: "${kvToolPath}",
      target: "gateway",
    },
  },

  agents: {
    beige: {
      model: {
        provider: "anthropic",
        model: "claude-sonnet-4-6",
        thinkingLevel: "off",
      },
      tools: ["kv"],
      sandbox: {
        image: "beige-sandbox:latest",
      },
    },
  },
}
`;
}

// ── Helpers ──────────────────────────────────────────────────────────────────

function ensureDir(p: string): void {
  mkdirSync(p, { recursive: true });
}

/**
 * Copy src → dst only if dst does not already exist.
 * Works for both files and directories (recursive).
 * Returns true when the copy was performed.
 */
function safeCopy(src: string, dst: string): boolean {
  if (existsSync(dst)) return false;

  const stat = statSync(src);
  if (stat.isDirectory()) {
    cpSync(src, dst, { recursive: true });
  } else {
    writeFileSync(dst, ""); // create placeholder so cpSync isn't needed for files
    cpSync(src, dst);
  }
  return true;
}

// ── Public API ───────────────────────────────────────────────────────────────

export interface SetupResult {
  /** Paths that were newly created. */
  created: string[];
  /** Paths that already existed and were skipped. */
  skipped: string[];
}

/**
 * Run beige first-time setup.
 */
export async function runSetup(_options: { force?: boolean } = {}): Promise<SetupResult> {
  const created: string[] = [];
  const skipped: string[] = [];

  const dir = beigeDir();
  const toolsDst = resolve(dir, "tools");
  const configDst = resolve(dir, "config.json5");

  ensureDir(dir);

  // ── Copy bundled tools ─────────────────────────────────────────────────────

  const toolsSrc = resolve(packageRoot(), "tools");

  if (existsSync(toolsSrc)) {
    ensureDir(toolsDst);

    const toolEntries = readdirSync(toolsSrc);
    for (const entry of toolEntries) {
      const src = join(toolsSrc, entry);
      const dst = join(toolsDst, entry);
      const copied = safeCopy(src, dst);
      if (copied) {
        created.push(dst);
      } else {
        skipped.push(dst);
      }
    }
  }

  // ── Write default config ───────────────────────────────────────────────────

  if (existsSync(configDst)) {
    skipped.push(configDst);
  } else {
    const kvToolPath = resolve(toolsDst, "kv");
    writeFileSync(configDst, defaultConfig(kvToolPath), "utf-8");
    created.push(configDst);
  }

  return { created, skipped };
}
